name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          python3-dev \
          build-essential \
          libffi-dev \
          libssl-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libsqlite3-dev \
          libgdbm-dev \
          libdb5.3-dev \
          libbz2-dev \
          libexpat1-dev \
          liblzma-dev \
          zlib1g-dev \
          cython3 \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install --user buildozer
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Configure Buildozer
      run: |
        buildozer init
        echo "title = 黄金监控" >> buildozer.spec
        echo "package.name = goldmonitor" >> buildozer.spec
        echo "requirements = python3, kivy, kivymd, requests" >> buildozer.spec
        echo "android.permissions = INTERNET, VIBRATE" >> buildozer.spec
        echo "source.main = main19.py" >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas,ttc,ttf" >> buildozer.spec

    # --- 关键的许可证修复步骤（修改后）---
    - name: Accept Android SDK Licenses (FORCE - Buildozer Path)
      run: |
        # 找到Buildozer使用的Android SDK路径，并在此路径下创建许可证文件
        SDK_PATH=$(find ~/.buildozer/android/platform -name "android-sdk" -type d | head -1)
        if [ -z "$SDK_PATH" ]; then
          SDK_PATH="/home/runner/.buildozer/android/platform/android-sdk"
        fi
        echo "Target SDK path: $SDK_PATH"

        # 创建许可证目录
        mkdir -p "$SDK_PATH/licenses"

        # 写入强力许可证接受文件
        echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$SDK_PATH/licenses/android-sdk-license"
        echo -e "84831b9409646a918e30573bab4c9c91346d8abd\nd975f751698a77b662f1254ddbeed3901e976f5a" > "$SDK_PATH/licenses/android-sdk-preview-license"
        echo "601085b94cd77f0b54ff86406957099ebe79c4d6" > "$SDK_PATH/licenses/android-googletv-license"
        echo "33b6a2b64607f11b759f320ef9dff4ae5c47d97a" > "$SDK_PATH/licenses/android-sdk-arm-dbt-license"
        echo "e9acab5b5fbb560a72cfaecce8946896ff6aab9d" > "$SDK_PATH/licenses/google-gdk-license"

        echo "Android SDK licenses have been written directly to Buildozer's SDK path."

    # --- 可选的终极后备方案（如果上面的方案仍失败，请启用）---
    # - name: Install Android SDK Components Manually (Fallback)
    #   run: |
    #     # 确保SDK管理器可用
    #     yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --update
    #     # 安装一个通用的平台和构建工具（例如 API 33）
    #     yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools"
    #     # 尝试再次接受所有许可
    #     yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses || true
    #     echo "Common Android SDK components installed as fallback."

    - name: Build APK
      timeout-minutes: 60
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: gold-monitor-apk
        path: bin/*.apk
        retention-days: 7