name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          python3-dev \
          build-essential \
          libffi-dev \
          libssl-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libsqlite3-dev \
          libgdbm-dev \
          libdb5.3-dev \
          libbz2-dev \
          libexpat1-dev \
          liblzma-dev \
          zlib1g-dev \
          cython3 \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install --user buildozer
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Configure Buildozer
      run: |
        # 1. 强制重新初始化，生成 buildozer.spec
        echo "正在初始化Buildozer并生成配置文件..."
        rm -f buildozer.spec
        buildozer init -y
        
        # 2. 验证文件是否生成
        if [ ! -f "buildozer.spec" ]; then
          echo "错误：buildozer.spec 文件未能生成！"
          exit 1
        fi
        echo "✅ buildozer.spec 文件已生成"
        ls -la buildozer.spec
        
        # 3. 使用sed命令直接修改spec文件中的关键配置项
        # 如果你的仓库里没有sed，也可以逐行echo追加，但sed更精准
        echo "正在配置 buildozer.spec 文件..."
        sed -i "s|^title = .*|title = 黄金监控|g" buildozer.spec
        sed -i "s|^package.name = .*|package.name = goldmonitor|g" buildozer.spec
        sed -i "s|^package.domain = .*|package.domain = org.goldmonitor|g" buildozer.spec
        sed -i "s|^source.dir = .*|source.dir = .|g" buildozer.spec
        sed -i "s|^source.main = .*|source.main = main19.py|g" buildozer.spec
        sed -i "s|^source.include_exts = .*|source.include_exts = py,png,jpg,kv,atlas,ttc,ttf|g" buildozer.spec
        sed -i "s|^requirements = .*|requirements = python3,kivy,kivymd,requests|g" buildozer.spec
        sed -i "s|^android.api = .*|android.api = 33|g" buildozer.spec
        sed -i "s|^android.minapi = .*|android.minapi = 21|g" buildozer.spec
        sed -i "s|^android.sdk = .*|android.sdk = 33|g" buildozer.spec
        sed -i "s|^android.ndk = .*|android.ndk = 25.1.8937393|g" buildozer.spec
        sed -i "s|^android.permissions = .*|android.permissions = INTERNET,VIBRATE|g" buildozer.spec
        sed -i "s|^orientation = .*|orientation = portrait|g" buildozer.spec
        
        # 4. 显示关键配置以验证
        echo "--- 配置完成，检查关键项 ---"
        grep -E "^(title|package\.name|package\.domain|source\.main|requirements|android\.api|android\.sdk)" buildozer.spec
        echo "✅ buildozer.spec 配置完成"

    # --- 核心修复：手动安装并接受SDK许可 ---
    - name: Update Android SDK Tools
      run: |
        # 设置环境变量指向Buildozer的SDK路径
        export ANDROID_HOME="/home/runner/.buildozer/android/platform/android-sdk"
        export ANDROID_SDK_ROOT="$ANDROID_HOME"
        echo "Android SDK Home: $ANDROID_HOME"
        
        # 首先，非交互式地更新SDK工具本身
        yes | $ANDROID_HOME/tools/bin/sdkmanager --update --channel=0 > /dev/null 2>&1
        echo "SDK tools updated."

    - name: Install Base Android SDK Platform
      run: |
        export ANDROID_HOME="/home/runner/.buildozer/android/platform/android-sdk"
        export ANDROID_SDK_ROOT="$ANDROID_HOME"
        
        # 安装一个基础的 Android 平台 (API 33)
        yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-33" > /dev/null 2>&1
        echo "Base Android platform (API 33) installed."

    - name: Install Specific Build-Tools and Accept Licenses
      run: |
        export ANDROID_HOME="/home/runner/.buildozer/android/platform/android-sdk"
        export ANDROID_SDK_ROOT="$ANDROID_HOME"
        
        # 尝试安装一个通用的构建工具版本 (例如 33.0.2)，并强制接受许可
        # 使用 `sdkmanager --licenses` 并配合 `yes` 命令尝试一次性接受所有
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null 2>&1 || true
        
        # 然后安装构建工具
        yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;33.0.2" > /dev/null 2>&1
        echo "Android SDK Build-Tools 33.0.2 installed (licenses forced accepted)."

    - name: Build APK
      timeout-minutes: 60
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: gold-monitor-apk
        path: bin/*.apk
        retention-days: 7